### ISSUE TITLE
How to compile powerline-client in setup.py?

### ISSUE THREAD

**Issue by Lokaltog** [kovidgoyal/powerline-daemon#1]
Before copying any code into the main powerline project I think we need to find a solution that allows automatic compiling of powerline-client.c when installing Powerline via setup.py. Distutils only appears to support Python extension compiling by default, and the only other information I've found on this subject is [this thread on stackoverflow](http://stackoverflow.com/questions/1754966/how-can-i-run-a-makefile-in-setup-py).

Do you have any suggestion on how this can be done in a clean way? Or is it more practical to keep powerline-daemon in its own repo?

**Comment by kovidgoyal** [comment]
You can do whatever you want in setup.py, compile stuff, install it, etc. Basically define your own setup function/class that calls the distutils code as part of its operation. The tricky part (because distutils is designed so badly) is extracting the compiler information and script installation location from distutils. If you spend a bit of time reading through the distutils code it should be fairly easy to figure out, if not let me know and I'll cook something up.

**Comment by Lokaltog** [comment]
Yeah, as you mention the issue is how to extract compiler info. I was thinking a quick fix might be to create a Makefile and run make from setup.py and move the resulting binary into `scripts/` before running the rest of the setup script, but it feels like a halfway/dirty solution to the problem.

**Comment by kovidgoyal** [comment]
It's not a big deal to find the compiler info, I've done it a few times
before, I'll see if I can dig up my old code.

**Comment by kovidgoyal** [comment]
Here's the basic idea

``` python
from distutils.ccompiler import new_compiler
compiler = new_compiler()
objects = compiler.compile([source_file])[0]
exe_file = compiler.link_executable(objects, 'powerline-client.exe', output_dir='whatever')
```

This will use the same compiler as python itself, which means gcc on unix and msvc on windows.

**Comment by kovidgoyal** [comment]
It may be that the compiler object does unneccessary things like linking with the python dll, in which case you can just get the executable directly as compiler.compiler and call it with subprocess. Since powerline-client needs no libraries it's a very simple compile.

**Comment by kovidgoyal** [comment]
I committed a rudimentary setup.py script to show how it can be done.

**Comment by Lokaltog** [comment]
Excellent, thanks!
