### ISSUE TITLE
Performance gain

### ISSUE THREAD

**Issue by wernight** [kovidgoyal/powerline-daemon#11]
Could you explain the expected performance gain along with why/how? I heard for example Powerline Git status using file system monitoring but I didn't find it faster, may be it's part of this project.

**Comment by kovidgoyal** [comment]
The daemon allows powerline to use inotify to avoid having to run git every time the prompt is rendered. git is only run when something actually changes. This only works on linux.

**Comment by wernight** [comment]
I'm on Linux with powerline and inotify-tools but it's still slow when I
enable Powerline in my ZSH.
